Repository FrontMen/fm-hours, pull requests merged in 2021-08, with the labels that each got.

#219 Feature/email reminder
  components/timesheets/weekly-timesheet-admin-footer.vue
  helpers/email.ts
  pages/records/_start_timestamp/_date.vue
  pages/records/index.vue
  pages/timesheets/_employee_id/_start_timestamp.vue
  pages/timesheets/index.vue
  store/timesheets/actions.ts
  types/timesheets.d.ts
Labels: Timesheets, enhancement

#227 Feat: message history
  components/records/comment-block.vue
  composables/useTimesheet.ts
  helpers/helpers.ts
  pages/records/index.vue
  store/timesheets/actions.ts
  store/timesheets/mutations.ts
  store/timesheets/state.ts
  types/timesheets.d.ts
Labels: enhancement

#233 fix(records): show 0 instead of NaN
  components/records/weekly-timesheet-row.vue
Labels: bug

#230 feat: records add notification when workscheme can't be fetched
  components/records/weekly-timesheet-totals-row.vue
  pages/records/index.vue
  services/work-scheme-service.ts
  store/records/actions.ts
  store/records/mutations.ts
  store/records/state.ts
  types/records.d.ts
Labels: enhancement
