Repository FrontMen/fm-hours, pull requests merged in 2021-07, with the labels that each got.

#128 Feat/intracto auth
  nuxt.config.ts
  package.json
  plugins/services.ts
  services/auth-service.ts
  services/employees-service.ts
  store/employee/actions.ts
  types/api.d.ts
  types/employee.d.ts
  types/index.d.ts
  yarn.lock
Labels: enhancement

#143 fix(auth): add full url and clear cookie
  services/auth-service.ts
  store/employee/actions.ts
Labels: bug

#144 fix(auth): use new instace of authService on logout
  store/employee/actions.ts
Labels: bug

#158 Fix/clear empty timesheet
  composables/useTimesheet.ts
  services/timesheets-service.ts
  store/timesheets/actions.ts
Labels: bug

#167 Feat: work schema api
  components/app/top-bar.vue
  components/records/navigation-buttons.vue
  components/records/weekly-timesheet-row.vue
  components/records/weekly-timesheet-totals-row.vue
  components/records/weekly-timesheet.vue
  components/reports/reports-table.vue
  components/timesheets/weekly-pending-timesheet.vue
  components/timesheets/weekly-timesheet-admin-footer.vue
  composables/useMonthlyProjectsReport.ts
  composables/useMonthlyTotalsReport.ts
  composables/useTimesheet.ts
  helpers/dates.ts
  helpers/helpers.ts
  helpers/timesheet.ts
  pages/customers/_customer_id.vue
  pages/customers/index.vue
  pages/employees/_employee_id.vue
  pages/employees/index.vue
  pages/holidays.vue
  pages/month.vue
  pages/records.vue
  pages/timesheets/index.vue
  plugins/services.ts
  services/employees-service.ts
  services/time-records-service.ts
  services/work-scheme-service.ts
  store/employees/actions.ts
  store/employees/getters.ts
  store/employees/mutations.ts
  store/filters/actions.ts
  store/filters/getters.ts
  store/filters/mutations.ts
  store/filters/state.ts
  store/records/actions.ts
  store/records/mutations.ts
  store/timesheets/getters.ts
  types/filters.d.ts
  types/records.d.ts
  types/timesheets.d.ts
  types/work-scheme.d.ts
Labels: enhancement

#174 Feat: remove create employee
  functions/src/createEmployee.ts
  functions/src/index.ts
  helpers/employee.ts
  store/employee/actions.ts
Labels: enhancement

#185 fix(employee): remove query by id
  services/employees-service.ts
Labels: bug

#211 fix: change layout of monthly nav to make it more predictable
  components/reports/month-navigation-buttons.vue
  pages/records.vue
Labels: enhancement

#210 fix: make sure csv only exports correct tables
  components/reports/reports-table.vue
  pages/reports.vue
Labels: Reports

#192 feat(records): grey ou part time days
  components/records/weekly-timesheet-row.vue
  components/records/weekly-timesheet.vue
  helpers/dates.ts
  helpers/record-status.ts
  helpers/timesheet.ts
  helpers/validation.ts
  services/auth-service.ts
  services/employees-service.ts
  services/timesheets-service.ts
  services/work-scheme-service.ts
  store/records/actions.ts
  store/reports/actions.ts
  types/records.d.ts
  types/work-scheme.d.ts
Labels: enhancement

#213 fix(records): cancel saving when changing week
  composables/useTimesheet.ts
  pages/records.vue
Labels: bug

#217 feat: prompt when changing isBillable flag of a project
  pages/customers/_customer_id.vue
Labels: Customers, enhancement

#214 Feature/employee filter by
  helpers/timesheet.ts
  helpers/validation.ts
  pages/customers/index.vue
  pages/employees/index.vue
  services/auth-service.ts
  services/employees-service.ts
  services/timesheets-service.ts
  store/filters/actions.ts
  store/filters/getters.ts
  store/filters/mutations.ts
  store/filters/state.ts
  store/records/actions.ts
  store/reports/actions.ts
  types/filters.d.ts
Labels: Employees, enhancement
